all: hw2-1a hw2-1b hw2-1c hw2-2a hw2-2b hw2-2c
hw2-1a: hw2-1a.c
hw2-1b: hw2-1b.c
hw2-1c: hw2-1c.c
hw2-2a: hw2-2a.c
hw2-2b: hw2-2b.c
hw2-2c: hw2-2c.c
clean:
	rm -rf hw2-1a hw2-1b hw2-1c hw2-2a hw2-2b hw2-2c
